version: '3.9'
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:0-20
    container_name: runninghill_api
    volumes:
      - ../..:/workspaces:cached
      - logs:/workspaces/logs
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command: ["postgres", "-c", "log_statement=all"]

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    ports:
      - "5050:80"
volumes:
  logs:
  postgres-data:  
  pgadmin-data: